const APIFY_API_KEY = process.env.APIFY_API_KEY || '';

// Apify Actor IDs from the N8N workflow
const YOUTUBE_SEARCH_ACTOR = 'h7sDV53CddomktSi5';
const EMAIL_SCRAPER_ACTOR = 'a5LvabQAGP2d5pWIH';

export interface YouTubeSearchResult {
  channelName: string;
  channelUrl: string;
  channelId: string;
  numberOfSubscribers: number;
  descriptionLinks?: string[];
  title?: string;
  description?: string;
}

export interface EmailScraperResult {
  email: string[];
  status: 'succ' | 'none' | 'error';
}

/**
 * Search YouTube channels by keyword using Apify
 */
export async function searchYouTubeChannels(
  keyword: string,
  maxResults: number = 50
): Promise<YouTubeSearchResult[]> {
  const url = `https://api.apify.com/v2/acts/${YOUTUBE_SEARCH_ACTOR}/run-sync-get-dataset-items`;

  const response = await fetch(url, {
    method: 'POST',
    headers: {
      'Accept': 'application/json',
      'Authorization': `Bearer ${APIFY_API_KEY}`,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({
      downloadSubtitles: false,
      hasCC: false,
      hasLocation: false,
      hasSubtitles: false,
      is360: false,
      is3D: false,
      is4K: false,
      isBought: false,
      isHD: false,
      isHDR: false,
      isLive: false,
      isVR180: false,
      maxResultStreams: 0,
      maxResults: maxResults,
      maxResultsShorts: 0,
      oldestPostDate: '2024-01-01',
      preferAutoGeneratedSubtitles: false,
      saveSubsToKVS: false,
      searchQueries: [keyword],
    }),
  });

  if (!response.ok) {
    const errorText = await response.text();
    throw new Error(`Apify YouTube search failed: ${response.status} - ${errorText}`);
  }

  const data = await response.json();
  return data as YouTubeSearchResult[];
}

/**
 * Scrape email from a YouTube channel URL using Apify
 */
export async function scrapeChannelEmail(channelUrl: string): Promise<EmailScraperResult> {
  const url = `https://api.apify.com/v2/acts/${EMAIL_SCRAPER_ACTOR}/run-sync-get-dataset-items`;

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'application/json',
        'Authorization': `Bearer ${APIFY_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        url: channelUrl,
      }),
    });

    if (!response.ok) {
      console.error(`Email scraper failed for ${channelUrl}: ${response.status}`);
      return { email: [], status: 'error' };
    }

    const data = await response.json();

    // The email scraper returns an array, get the first item
    if (Array.isArray(data) && data.length > 0) {
      return {
        email: data[0].email || [],
        status: data[0].email?.length > 0 ? 'succ' : 'none',
      };
    }

    return { email: [], status: 'none' };
  } catch (error) {
    console.error(`Email scraper error for ${channelUrl}:`, error);
    return { email: [], status: 'error' };
  }
}
