export interface Niche {
  id: string;
  name: string;
  category: string;
  subcategory: string;
  searchKeywords: string[];
  description?: string;
}

export interface NicheCategory {
  id: string;
  name: string;
  icon: string;
  subcategories: {
    id: string;
    name: string;
    niches: Niche[];
  }[];
}

export const NICHE_CATEGORIES: NicheCategory[] = [
  // ============================================
  // WEALTH - Money, Business, Career
  // ============================================
  {
    id: 'wealth',
    name: 'Wealth',
    icon: '💰',
    subcategories: [
      {
        id: 'online-business',
        name: 'Online Business Models',
        niches: [
          {
            id: 'dropshipping',
            name: 'Dropshipping',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['dropshipping tutorial', 'shopify dropshipping', 'dropshipping for beginners', 'ecommerce dropshipping'],
          },
          {
            id: 'amazon-fba',
            name: 'Amazon FBA',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['amazon fba', 'amazon fba for beginners', 'private label amazon', 'amazon seller'],
          },
          {
            id: 'amazon-wholesale',
            name: 'Amazon Wholesale',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['amazon wholesale', 'wholesale fba', 'amazon wholesale for beginners'],
          },
          {
            id: 'amazon-arbitrage',
            name: 'Amazon Arbitrage',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['retail arbitrage', 'online arbitrage amazon', 'amazon arbitrage'],
          },
          {
            id: 'print-on-demand',
            name: 'Print on Demand',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['print on demand', 'printify tutorial', 'merch by amazon', 'teespring', 'redbubble'],
          },
          {
            id: 'affiliate-marketing',
            name: 'Affiliate Marketing',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['affiliate marketing', 'affiliate marketing for beginners', 'how to make money with affiliate marketing'],
          },
          {
            id: 'course-creation',
            name: 'Course Creation',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['how to create online course', 'course creation', 'sell online courses', 'teachable', 'kajabi tutorial'],
          },
          {
            id: 'coaching-business',
            name: 'Coaching Business',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['start coaching business', 'online coaching', 'high ticket coaching', 'life coach business'],
          },
          {
            id: 'consulting-business',
            name: 'Consulting Business',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['start consulting business', 'become a consultant', 'consulting for beginners'],
          },
          {
            id: 'smma',
            name: 'Social Media Marketing Agency',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['smma', 'social media marketing agency', 'start smma', 'smma for beginners'],
          },
          {
            id: 'digital-marketing-agency',
            name: 'Digital Marketing Agency',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['digital marketing agency', 'start marketing agency', 'agency business model'],
          },
          {
            id: 'web-design-agency',
            name: 'Web Design Agency',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['web design agency', 'start web design business', 'freelance web designer'],
          },
          {
            id: 'saas',
            name: 'SaaS (Software as a Service)',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['build saas', 'saas business', 'micro saas', 'start saas company'],
          },
          {
            id: 'freelancing',
            name: 'Freelancing',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['freelancing for beginners', 'upwork tutorial', 'fiverr success', 'freelance business'],
          },
          {
            id: 'content-creation-business',
            name: 'Content Creation Business',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['content creator business', 'monetize content', 'full time content creator'],
          },
          {
            id: 'newsletter-business',
            name: 'Newsletter Business',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['newsletter business', 'substack', 'beehiiv', 'paid newsletter', 'email newsletter business'],
          },
          {
            id: 'community-business',
            name: 'Community Business',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['skool community', 'paid community', 'membership community', 'discord community business'],
          },
          {
            id: 'digital-products',
            name: 'Digital Products',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['sell digital products', 'digital product ideas', 'passive income digital products', 'gumroad'],
          },
          {
            id: 'notion-templates',
            name: 'Notion Templates',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['sell notion templates', 'notion template business', 'notion creator'],
          },
          {
            id: 'etsy-digital',
            name: 'Etsy Digital Products',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['etsy digital products', 'etsy printables', 'sell on etsy', 'etsy shop'],
          },
          {
            id: 'info-products',
            name: 'Information Products',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['info products', 'ebook business', 'sell ebooks', 'information marketing'],
          },
          {
            id: 'faceless-youtube',
            name: 'Faceless YouTube Channels',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['faceless youtube', 'youtube automation', 'cash cow youtube', 'faceless channel'],
          },
          {
            id: 'ai-automation-agency',
            name: 'AI Automation Agency',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['ai automation agency', 'aaa business', 'ai agency', 'sell ai services'],
          },
          {
            id: 'lead-generation',
            name: 'Lead Generation Business',
            category: 'wealth',
            subcategory: 'online-business',
            searchKeywords: ['lead generation business', 'lead gen agency', 'sell leads'],
          },
        ],
      },
      {
        id: 'trading-investing',
        name: 'Trading & Investing',
        niches: [
          {
            id: 'day-trading',
            name: 'Day Trading',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['day trading', 'day trading for beginners', 'day trader', 'how to day trade'],
          },
          {
            id: 'swing-trading',
            name: 'Swing Trading',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['swing trading', 'swing trading strategy', 'swing trade stocks'],
          },
          {
            id: 'options-trading',
            name: 'Options Trading',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['options trading', 'options for beginners', 'call options', 'put options', 'options strategy'],
          },
          {
            id: 'forex-trading',
            name: 'Forex Trading',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['forex trading', 'forex for beginners', 'currency trading', 'fx trading'],
          },
          {
            id: 'futures-trading',
            name: 'Futures Trading',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['futures trading', 'futures for beginners', 'es futures', 'trading futures'],
          },
          {
            id: 'crypto-trading',
            name: 'Crypto Trading',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['crypto trading', 'bitcoin trading', 'cryptocurrency trading', 'altcoin trading'],
          },
          {
            id: 'crypto-investing',
            name: 'Crypto Investing',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['crypto investing', 'bitcoin investing', 'cryptocurrency for beginners', 'defi'],
          },
          {
            id: 'stock-investing',
            name: 'Stock Market Investing',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['stock market investing', 'how to invest in stocks', 'stock market for beginners', 'value investing'],
          },
          {
            id: 'dividend-investing',
            name: 'Dividend Investing',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['dividend investing', 'dividend stocks', 'passive income dividends', 'dividend portfolio'],
          },
          {
            id: 'index-fund-investing',
            name: 'Index Fund Investing',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['index fund investing', 'index funds for beginners', 'vanguard', 'passive investing'],
          },
          {
            id: 'technical-analysis',
            name: 'Technical Analysis',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['technical analysis', 'chart patterns', 'trading indicators', 'price action'],
          },
          {
            id: 'algorithmic-trading',
            name: 'Algorithmic Trading',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['algorithmic trading', 'algo trading', 'trading bots', 'automated trading'],
          },
          {
            id: 'prop-trading',
            name: 'Prop Firm Trading',
            category: 'wealth',
            subcategory: 'trading-investing',
            searchKeywords: ['prop firm', 'funded trader', 'ftmo', 'prop trading', 'funded account'],
          },
        ],
      },
      {
        id: 'real-estate',
        name: 'Real Estate',
        niches: [
          {
            id: 'real-estate-investing',
            name: 'Real Estate Investing',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['real estate investing', 'real estate investing for beginners', 'rental property investing'],
          },
          {
            id: 'rental-properties',
            name: 'Rental Properties',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['rental property', 'buy rental property', 'landlord tips', 'rental income'],
          },
          {
            id: 'airbnb-str',
            name: 'Airbnb / Short-Term Rentals',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['airbnb business', 'short term rental', 'airbnb hosting', 'vrbo', 'airbnb arbitrage'],
          },
          {
            id: 'house-flipping',
            name: 'House Flipping',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['house flipping', 'flip houses', 'real estate flipping', 'fix and flip'],
          },
          {
            id: 'wholesaling',
            name: 'Wholesaling Real Estate',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['wholesaling real estate', 'wholesale houses', 'real estate wholesaling for beginners'],
          },
          {
            id: 'brrrr',
            name: 'BRRRR Strategy',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['brrrr strategy', 'brrrr real estate', 'buy rehab rent refinance repeat'],
          },
          {
            id: 'commercial-real-estate',
            name: 'Commercial Real Estate',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['commercial real estate', 'commercial property investing', 'commercial real estate investing'],
          },
          {
            id: 'multifamily',
            name: 'Multifamily Investing',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['multifamily investing', 'apartment investing', 'multifamily real estate'],
          },
          {
            id: 'land-investing',
            name: 'Land Investing',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['land investing', 'raw land investing', 'buy land', 'land flipping'],
          },
          {
            id: 'mobile-home-investing',
            name: 'Mobile Home Investing',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['mobile home investing', 'mobile home park', 'trailer park investing'],
          },
          {
            id: 'storage-units',
            name: 'Storage Unit Investing',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['storage unit investing', 'self storage business', 'storage facility'],
          },
          {
            id: 'real-estate-agent',
            name: 'Real Estate Agent Training',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['real estate agent', 'become real estate agent', 'realtor tips', 'real estate agent training'],
          },
          {
            id: 'real-estate-syndication',
            name: 'Real Estate Syndication',
            category: 'wealth',
            subcategory: 'real-estate',
            searchKeywords: ['real estate syndication', 'syndication investing', 'passive real estate'],
          },
        ],
      },
      {
        id: 'marketing-sales',
        name: 'Marketing & Sales',
        niches: [
          {
            id: 'digital-marketing',
            name: 'Digital Marketing',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['digital marketing', 'digital marketing tutorial', 'online marketing'],
          },
          {
            id: 'facebook-ads',
            name: 'Facebook Ads',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['facebook ads', 'meta ads', 'facebook advertising', 'fb ads tutorial'],
          },
          {
            id: 'google-ads',
            name: 'Google Ads',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['google ads', 'google ads tutorial', 'ppc advertising', 'adwords'],
          },
          {
            id: 'tiktok-ads',
            name: 'TikTok Ads',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['tiktok ads', 'tiktok advertising', 'tiktok ads tutorial'],
          },
          {
            id: 'youtube-ads',
            name: 'YouTube Ads',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['youtube ads', 'youtube advertising', 'video ads'],
          },
          {
            id: 'seo',
            name: 'SEO (Search Engine Optimization)',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['seo', 'seo tutorial', 'search engine optimization', 'seo for beginners', 'rank on google'],
          },
          {
            id: 'local-seo',
            name: 'Local SEO',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['local seo', 'google my business', 'local search', 'rank locally'],
          },
          {
            id: 'content-marketing',
            name: 'Content Marketing',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['content marketing', 'content strategy', 'content marketing tutorial'],
          },
          {
            id: 'email-marketing',
            name: 'Email Marketing',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['email marketing', 'email marketing tutorial', 'email copywriting', 'email list building'],
          },
          {
            id: 'copywriting',
            name: 'Copywriting',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['copywriting', 'copywriting tutorial', 'sales copy', 'how to write copy'],
          },
          {
            id: 'sales-training',
            name: 'Sales Training',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['sales training', 'how to sell', 'sales techniques', 'close more sales', 'sales skills'],
          },
          {
            id: 'high-ticket-sales',
            name: 'High Ticket Sales',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['high ticket sales', 'high ticket closing', 'sell high ticket', 'premium offers'],
          },
          {
            id: 'cold-outreach',
            name: 'Cold Outreach',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['cold email', 'cold outreach', 'cold calling', 'b2b outreach', 'lead generation'],
          },
          {
            id: 'funnel-building',
            name: 'Sales Funnels',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['sales funnel', 'clickfunnels', 'funnel building', 'marketing funnel'],
          },
          {
            id: 'conversion-optimization',
            name: 'Conversion Optimization',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['conversion optimization', 'cro', 'landing page optimization', 'increase conversions'],
          },
          {
            id: 'branding',
            name: 'Branding',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['branding', 'personal branding', 'brand strategy', 'build a brand'],
          },
          {
            id: 'influencer-marketing',
            name: 'Influencer Marketing',
            category: 'wealth',
            subcategory: 'marketing-sales',
            searchKeywords: ['influencer marketing', 'ugc creator', 'brand deals', 'sponsored content'],
          },
        ],
      },
      {
        id: 'career',
        name: 'Career & Professional',
        niches: [
          {
            id: 'career-change',
            name: 'Career Change',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['career change', 'switch careers', 'career transition', 'new career'],
          },
          {
            id: 'resume-linkedin',
            name: 'Resume & LinkedIn',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['resume tips', 'linkedin optimization', 'job search', 'linkedin profile'],
          },
          {
            id: 'interview-skills',
            name: 'Interview Skills',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['job interview', 'interview tips', 'ace the interview', 'interview questions'],
          },
          {
            id: 'salary-negotiation',
            name: 'Salary Negotiation',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['salary negotiation', 'negotiate salary', 'get a raise', 'increase salary'],
          },
          {
            id: 'remote-work',
            name: 'Remote Work',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['remote work', 'work from home', 'remote jobs', 'digital nomad'],
          },
          {
            id: 'tech-career',
            name: 'Breaking Into Tech',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['break into tech', 'tech career', 'get job in tech', 'tech industry'],
          },
          {
            id: 'software-engineering-career',
            name: 'Software Engineering Career',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['software engineer career', 'become software developer', 'coding career', 'programming job'],
          },
          {
            id: 'data-science-career',
            name: 'Data Science Career',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['data science career', 'become data scientist', 'data analyst career', 'break into data'],
          },
          {
            id: 'product-management',
            name: 'Product Management',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['product manager', 'product management', 'become product manager', 'pm career'],
          },
          {
            id: 'ux-design-career',
            name: 'UX Design Career',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['ux design career', 'become ux designer', 'ui ux career', 'ux portfolio'],
          },
          {
            id: 'cybersecurity-career',
            name: 'Cybersecurity Career',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['cybersecurity career', 'break into cybersecurity', 'security analyst', 'ethical hacking career'],
          },
          {
            id: 'leadership',
            name: 'Leadership & Management',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['leadership skills', 'management training', 'become a leader', 'executive coaching'],
          },
          {
            id: 'public-speaking',
            name: 'Public Speaking',
            category: 'wealth',
            subcategory: 'career',
            searchKeywords: ['public speaking', 'presentation skills', 'speak confidently', 'overcome fear of public speaking'],
          },
        ],
      },
      {
        id: 'personal-finance',
        name: 'Personal Finance',
        niches: [
          {
            id: 'budgeting',
            name: 'Budgeting',
            category: 'wealth',
            subcategory: 'personal-finance',
            searchKeywords: ['budgeting', 'how to budget', 'budget tips', 'money management'],
          },
          {
            id: 'debt-payoff',
            name: 'Debt Payoff',
            category: 'wealth',
            subcategory: 'personal-finance',
            searchKeywords: ['pay off debt', 'debt free', 'debt payoff', 'get out of debt'],
          },
          {
            id: 'credit-repair',
            name: 'Credit Repair',
            category: 'wealth',
            subcategory: 'personal-finance',
            searchKeywords: ['credit repair', 'fix credit', 'improve credit score', 'credit building'],
          },
          {
            id: 'fire',
            name: 'FIRE (Financial Independence)',
            category: 'wealth',
            subcategory: 'personal-finance',
            searchKeywords: ['fire movement', 'financial independence', 'retire early', 'fire lifestyle'],
          },
          {
            id: 'tax-strategies',
            name: 'Tax Strategies',
            category: 'wealth',
            subcategory: 'personal-finance',
            searchKeywords: ['tax strategies', 'reduce taxes', 'tax planning', 'tax tips'],
          },
          {
            id: 'retirement-planning',
            name: 'Retirement Planning',
            category: 'wealth',
            subcategory: 'personal-finance',
            searchKeywords: ['retirement planning', '401k', 'ira', 'retire wealthy', 'retirement savings'],
          },
        ],
      },
      {
        id: 'local-business',
        name: 'Local & Service Businesses',
        niches: [
          {
            id: 'pressure-washing',
            name: 'Pressure Washing Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['pressure washing business', 'power washing business', 'start pressure washing'],
          },
          {
            id: 'cleaning-business',
            name: 'Cleaning Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['cleaning business', 'start cleaning business', 'cleaning company', 'janitorial business'],
          },
          {
            id: 'landscaping-business',
            name: 'Landscaping Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['landscaping business', 'lawn care business', 'start landscaping'],
          },
          {
            id: 'auto-detailing',
            name: 'Auto Detailing Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['auto detailing business', 'car detailing business', 'mobile detailing'],
          },
          {
            id: 'hvac-business',
            name: 'HVAC Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['hvac business', 'start hvac company', 'hvac contractor'],
          },
          {
            id: 'roofing-business',
            name: 'Roofing Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['roofing business', 'start roofing company', 'roofing contractor'],
          },
          {
            id: 'plumbing-business',
            name: 'Plumbing Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['plumbing business', 'start plumbing company', 'plumber business'],
          },
          {
            id: 'electrical-business',
            name: 'Electrical Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['electrical business', 'electrician business', 'start electrical company'],
          },
          {
            id: 'construction-business',
            name: 'Construction Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['construction business', 'general contractor', 'start construction company'],
          },
          {
            id: 'photography-business',
            name: 'Photography Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['photography business', 'start photography business', 'wedding photographer business'],
          },
          {
            id: 'videography-business',
            name: 'Videography Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['videography business', 'video production business', 'start videography'],
          },
          {
            id: 'gym-fitness-business',
            name: 'Gym / Fitness Studio',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['open gym', 'fitness studio business', 'start gym', 'fitness business'],
          },
          {
            id: 'restaurant-business',
            name: 'Restaurant Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['restaurant business', 'open restaurant', 'food business', 'start restaurant'],
          },
          {
            id: 'food-truck',
            name: 'Food Truck Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['food truck business', 'start food truck', 'food truck tips'],
          },
          {
            id: 'vending-machine',
            name: 'Vending Machine Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['vending machine business', 'passive income vending', 'vending business'],
          },
          {
            id: 'laundromat',
            name: 'Laundromat Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['laundromat business', 'coin laundry business', 'buy laundromat'],
          },
          {
            id: 'car-wash',
            name: 'Car Wash Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['car wash business', 'start car wash', 'car wash owner'],
          },
          {
            id: 'atm-business',
            name: 'ATM Business',
            category: 'wealth',
            subcategory: 'local-business',
            searchKeywords: ['atm business', 'atm machine business', 'passive income atm'],
          },
        ],
      },
      {
        id: 'professional-services',
        name: 'Professional Services',
        niches: [
          {
            id: 'insurance-agent',
            name: 'Insurance Agent',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['insurance agent', 'sell insurance', 'insurance sales', 'life insurance agent'],
          },
          {
            id: 'mortgage-broker',
            name: 'Mortgage Broker',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['mortgage broker', 'loan officer', 'mortgage business', 'mortgage training'],
          },
          {
            id: 'financial-advisor',
            name: 'Financial Advisor',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['financial advisor', 'financial planner', 'wealth management', 'cfp'],
          },
          {
            id: 'bookkeeping',
            name: 'Bookkeeping Business',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['bookkeeping business', 'start bookkeeping', 'virtual bookkeeper'],
          },
          {
            id: 'accounting',
            name: 'Accounting Practice',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['accounting business', 'cpa firm', 'start accounting practice'],
          },
          {
            id: 'law-practice',
            name: 'Law Practice',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['law firm marketing', 'solo attorney', 'start law practice', 'legal marketing'],
          },
          {
            id: 'medical-practice',
            name: 'Medical Practice',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['medical practice', 'start medical practice', 'private practice physician'],
          },
          {
            id: 'dental-practice',
            name: 'Dental Practice',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['dental practice', 'dentist business', 'dental marketing'],
          },
          {
            id: 'chiropractic',
            name: 'Chiropractic Practice',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['chiropractic practice', 'chiropractor business', 'chiropractic marketing'],
          },
          {
            id: 'therapy-practice',
            name: 'Therapy Practice',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['private practice therapist', 'therapy practice', 'counseling business'],
          },
          {
            id: 'personal-training-business',
            name: 'Personal Training Business',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['personal training business', 'online personal trainer', 'pt business'],
          },
          {
            id: 'nutrition-coaching-business',
            name: 'Nutrition Coaching Business',
            category: 'wealth',
            subcategory: 'professional-services',
            searchKeywords: ['nutrition coaching business', 'online nutrition coach', 'dietitian business'],
          },
        ],
      },
    ],
  },

  // ============================================
  // HEALTH - Physical, Mental, Spiritual
  // ============================================
  {
    id: 'health',
    name: 'Health',
    icon: '💪',
    subcategories: [
      {
        id: 'fitness',
        name: 'Fitness & Exercise',
        niches: [
          {
            id: 'weight-loss',
            name: 'Weight Loss',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['weight loss', 'lose weight', 'fat loss', 'how to lose weight'],
          },
          {
            id: 'muscle-building',
            name: 'Muscle Building',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['build muscle', 'muscle building', 'bodybuilding', 'gain muscle', 'hypertrophy'],
          },
          {
            id: 'strength-training',
            name: 'Strength Training',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['strength training', 'powerlifting', 'get stronger', 'barbell training'],
          },
          {
            id: 'calisthenics',
            name: 'Calisthenics',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['calisthenics', 'bodyweight workout', 'calisthenics for beginners', 'street workout'],
          },
          {
            id: 'home-workouts',
            name: 'Home Workouts',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['home workout', 'workout at home', 'no gym workout', 'home fitness'],
          },
          {
            id: 'crossfit',
            name: 'CrossFit',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['crossfit', 'crossfit workout', 'crossfit training', 'wod'],
          },
          {
            id: 'hiit',
            name: 'HIIT Training',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['hiit', 'hiit workout', 'high intensity interval training', 'hiit cardio'],
          },
          {
            id: 'running',
            name: 'Running',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['running', 'how to run', 'marathon training', 'running for beginners', '5k training'],
          },
          {
            id: 'cycling',
            name: 'Cycling',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['cycling', 'bike training', 'cycling workout', 'cyclist training'],
          },
          {
            id: 'swimming',
            name: 'Swimming',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['swimming', 'learn to swim', 'swim faster', 'swimming technique'],
          },
          {
            id: 'yoga',
            name: 'Yoga',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['yoga', 'yoga for beginners', 'yoga workout', 'yoga flow'],
          },
          {
            id: 'pilates',
            name: 'Pilates',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['pilates', 'pilates workout', 'pilates for beginners', 'pilates at home'],
          },
          {
            id: 'mobility-flexibility',
            name: 'Mobility & Flexibility',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['mobility', 'flexibility', 'stretching', 'improve mobility', 'mobility routine'],
          },
          {
            id: 'posture',
            name: 'Posture Correction',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['posture correction', 'fix posture', 'better posture', 'posture exercises'],
          },
          {
            id: 'over-40-fitness',
            name: 'Fitness Over 40',
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['fitness over 40', 'workout over 50', 'exercise for seniors', 'fit after 40'],
          },
          {
            id: 'womens-fitness',
            name: "Women's Fitness",
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['womens fitness', 'workout for women', 'female fitness', 'women weight training'],
          },
          {
            id: 'mens-fitness',
            name: "Men's Fitness",
            category: 'health',
            subcategory: 'fitness',
            searchKeywords: ['mens fitness', 'workout for men', 'male fitness', 'get shredded'],
          },
        ],
      },
      {
        id: 'combat-sports',
        name: 'Combat Sports & Martial Arts',
        niches: [
          {
            id: 'boxing',
            name: 'Boxing',
            category: 'health',
            subcategory: 'combat-sports',
            searchKeywords: ['boxing', 'learn boxing', 'boxing training', 'boxing technique'],
          },
          {
            id: 'mma',
            name: 'MMA',
            category: 'health',
            subcategory: 'combat-sports',
            searchKeywords: ['mma', 'mixed martial arts', 'mma training', 'ufc training'],
          },
          {
            id: 'bjj',
            name: 'Brazilian Jiu-Jitsu',
            category: 'health',
            subcategory: 'combat-sports',
            searchKeywords: ['bjj', 'brazilian jiu jitsu', 'jiu jitsu', 'bjj techniques'],
          },
          {
            id: 'wrestling',
            name: 'Wrestling',
            category: 'health',
            subcategory: 'combat-sports',
            searchKeywords: ['wrestling', 'wrestling training', 'wrestling techniques', 'learn wrestling'],
          },
          {
            id: 'muay-thai',
            name: 'Muay Thai',
            category: 'health',
            subcategory: 'combat-sports',
            searchKeywords: ['muay thai', 'kickboxing', 'muay thai training', 'thai boxing'],
          },
          {
            id: 'self-defense',
            name: 'Self Defense',
            category: 'health',
            subcategory: 'combat-sports',
            searchKeywords: ['self defense', 'self protection', 'learn self defense', 'street fight'],
          },
        ],
      },
      {
        id: 'sports-performance',
        name: 'Sports Performance',
        niches: [
          {
            id: 'golf',
            name: 'Golf',
            category: 'health',
            subcategory: 'sports-performance',
            searchKeywords: ['golf', 'golf swing', 'golf tips', 'improve golf game', 'golf lessons'],
          },
          {
            id: 'tennis',
            name: 'Tennis',
            category: 'health',
            subcategory: 'sports-performance',
            searchKeywords: ['tennis', 'tennis technique', 'tennis tips', 'improve tennis'],
          },
          {
            id: 'basketball',
            name: 'Basketball Training',
            category: 'health',
            subcategory: 'sports-performance',
            searchKeywords: ['basketball training', 'basketball skills', 'basketball workout', 'basketball drills'],
          },
          {
            id: 'soccer',
            name: 'Soccer Training',
            category: 'health',
            subcategory: 'sports-performance',
            searchKeywords: ['soccer training', 'football training', 'soccer skills', 'soccer drills'],
          },
          {
            id: 'football',
            name: 'Football Training',
            category: 'health',
            subcategory: 'sports-performance',
            searchKeywords: ['football training', 'football workout', 'nfl training', 'football speed'],
          },
          {
            id: 'baseball',
            name: 'Baseball Training',
            category: 'health',
            subcategory: 'sports-performance',
            searchKeywords: ['baseball training', 'hitting drills', 'pitching', 'baseball workout'],
          },
          {
            id: 'volleyball',
            name: 'Volleyball Training',
            category: 'health',
            subcategory: 'sports-performance',
            searchKeywords: ['volleyball training', 'volleyball tips', 'volleyball skills'],
          },
          {
            id: 'triathlon',
            name: 'Triathlon',
            category: 'health',
            subcategory: 'sports-performance',
            searchKeywords: ['triathlon', 'triathlon training', 'ironman training', 'triathlete'],
          },
        ],
      },
      {
        id: 'nutrition',
        name: 'Nutrition & Diet',
        niches: [
          {
            id: 'nutrition-coaching',
            name: 'Nutrition Coaching',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['nutrition', 'nutrition coaching', 'healthy eating', 'nutrition tips'],
          },
          {
            id: 'meal-prep',
            name: 'Meal Prep',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['meal prep', 'meal planning', 'weekly meal prep', 'healthy meal prep'],
          },
          {
            id: 'macro-counting',
            name: 'Macro Counting',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['macro counting', 'macros', 'iifym', 'flexible dieting', 'track macros'],
          },
          {
            id: 'keto',
            name: 'Keto Diet',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['keto', 'keto diet', 'ketogenic', 'low carb', 'keto for beginners'],
          },
          {
            id: 'carnivore',
            name: 'Carnivore Diet',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['carnivore diet', 'carnivore', 'meat only diet', 'all meat diet'],
          },
          {
            id: 'vegan',
            name: 'Vegan / Plant-Based',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['vegan', 'plant based', 'vegan diet', 'vegan nutrition', 'vegan fitness'],
          },
          {
            id: 'intermittent-fasting',
            name: 'Intermittent Fasting',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['intermittent fasting', 'fasting', 'if diet', 'omad', '16 8 fasting'],
          },
          {
            id: 'gut-health',
            name: 'Gut Health',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['gut health', 'digestive health', 'microbiome', 'heal gut', 'leaky gut'],
          },
          {
            id: 'sports-nutrition',
            name: 'Sports Nutrition',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['sports nutrition', 'athlete nutrition', 'performance nutrition', 'pre workout nutrition'],
          },
          {
            id: 'bodybuilding-nutrition',
            name: 'Bodybuilding Nutrition',
            category: 'health',
            subcategory: 'nutrition',
            searchKeywords: ['bodybuilding diet', 'bodybuilding nutrition', 'bulking diet', 'cutting diet'],
          },
        ],
      },
      {
        id: 'mental-health',
        name: 'Mental Health',
        niches: [
          {
            id: 'anxiety',
            name: 'Anxiety Management',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['anxiety', 'overcome anxiety', 'anxiety relief', 'manage anxiety', 'anxiety tips'],
          },
          {
            id: 'depression',
            name: 'Depression Support',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['depression', 'overcome depression', 'depression help', 'mental health'],
          },
          {
            id: 'stress-management',
            name: 'Stress Management',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['stress management', 'reduce stress', 'stress relief', 'manage stress'],
          },
          {
            id: 'trauma-healing',
            name: 'Trauma Healing',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['trauma healing', 'heal trauma', 'ptsd recovery', 'trauma recovery'],
          },
          {
            id: 'addiction-recovery',
            name: 'Addiction Recovery',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['addiction recovery', 'sobriety', 'quit addiction', 'recovery journey'],
          },
          {
            id: 'adhd',
            name: 'ADHD Management',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['adhd', 'adhd tips', 'adhd management', 'adhd strategies', 'adult adhd'],
          },
          {
            id: 'emotional-intelligence',
            name: 'Emotional Intelligence',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['emotional intelligence', 'eq', 'emotional awareness', 'emotional regulation'],
          },
          {
            id: 'boundaries',
            name: 'Boundaries',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['boundaries', 'set boundaries', 'healthy boundaries', 'boundary setting'],
          },
          {
            id: 'narcissistic-abuse-recovery',
            name: 'Narcissistic Abuse Recovery',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['narcissistic abuse', 'narcissist recovery', 'toxic relationship recovery', 'healing from narcissist'],
          },
          {
            id: 'self-esteem',
            name: 'Self-Esteem & Confidence',
            category: 'health',
            subcategory: 'mental-health',
            searchKeywords: ['self esteem', 'build confidence', 'self worth', 'confidence tips'],
          },
        ],
      },
      {
        id: 'mindset',
        name: 'Mindset & Personal Development',
        niches: [
          {
            id: 'mindset-coaching',
            name: 'Mindset Coaching',
            category: 'health',
            subcategory: 'mindset',
            searchKeywords: ['mindset', 'mindset coaching', 'growth mindset', 'success mindset'],
          },
          {
            id: 'habit-building',
            name: 'Habit Building',
            category: 'health',
            subcategory: 'mindset',
            searchKeywords: ['habits', 'build habits', 'habit building', 'atomic habits', 'good habits'],
          },
          {
            id: 'discipline',
            name: 'Discipline & Motivation',
            category: 'health',
            subcategory: 'mindset',
            searchKeywords: ['discipline', 'self discipline', 'motivation', 'stay motivated'],
          },
          {
            id: 'goal-setting',
            name: 'Goal Setting',
            category: 'health',
            subcategory: 'mindset',
            searchKeywords: ['goal setting', 'set goals', 'achieve goals', 'smart goals'],
          },
          {
            id: 'productivity',
            name: 'Productivity',
            category: 'health',
            subcategory: 'mindset',
            searchKeywords: ['productivity', 'be more productive', 'productivity tips', 'time management'],
          },
          {
            id: 'life-coaching',
            name: 'Life Coaching',
            category: 'health',
            subcategory: 'mindset',
            searchKeywords: ['life coaching', 'life coach', 'personal development', 'self improvement'],
          },
          {
            id: 'manifestation',
            name: 'Manifestation',
            category: 'health',
            subcategory: 'mindset',
            searchKeywords: ['manifestation', 'law of attraction', 'manifest', 'manifesting'],
          },
          {
            id: 'stoicism',
            name: 'Stoicism',
            category: 'health',
            subcategory: 'mindset',
            searchKeywords: ['stoicism', 'stoic philosophy', 'marcus aurelius', 'stoic mindset'],
          },
        ],
      },
      {
        id: 'spirituality',
        name: 'Spirituality & Wellness',
        niches: [
          {
            id: 'meditation',
            name: 'Meditation',
            category: 'health',
            subcategory: 'spirituality',
            searchKeywords: ['meditation', 'how to meditate', 'meditation for beginners', 'guided meditation'],
          },
          {
            id: 'breathwork',
            name: 'Breathwork',
            category: 'health',
            subcategory: 'spirituality',
            searchKeywords: ['breathwork', 'breathing exercises', 'breath work', 'wim hof breathing'],
          },
          {
            id: 'mindfulness',
            name: 'Mindfulness',
            category: 'health',
            subcategory: 'spirituality',
            searchKeywords: ['mindfulness', 'mindful living', 'present moment', 'mindfulness practice'],
          },
          {
            id: 'spiritual-awakening',
            name: 'Spiritual Awakening',
            category: 'health',
            subcategory: 'spirituality',
            searchKeywords: ['spiritual awakening', 'awakening', 'spiritual journey', 'consciousness'],
          },
          {
            id: 'energy-healing',
            name: 'Energy Healing',
            category: 'health',
            subcategory: 'spirituality',
            searchKeywords: ['energy healing', 'reiki', 'chakras', 'energy work', 'healing energy'],
          },
          {
            id: 'astrology',
            name: 'Astrology',
            category: 'health',
            subcategory: 'spirituality',
            searchKeywords: ['astrology', 'birth chart', 'zodiac', 'astrology reading'],
          },
          {
            id: 'tarot',
            name: 'Tarot',
            category: 'health',
            subcategory: 'spirituality',
            searchKeywords: ['tarot', 'tarot reading', 'learn tarot', 'tarot cards'],
          },
        ],
      },
      {
        id: 'longevity',
        name: 'Longevity & Biohacking',
        niches: [
          {
            id: 'longevity',
            name: 'Longevity / Anti-Aging',
            category: 'health',
            subcategory: 'longevity',
            searchKeywords: ['longevity', 'anti aging', 'live longer', 'longevity tips', 'aging well'],
          },
          {
            id: 'biohacking',
            name: 'Biohacking',
            category: 'health',
            subcategory: 'longevity',
            searchKeywords: ['biohacking', 'biohacker', 'optimize health', 'biohack'],
          },
          {
            id: 'supplements',
            name: 'Supplements',
            category: 'health',
            subcategory: 'longevity',
            searchKeywords: ['supplements', 'best supplements', 'supplement guide', 'vitamins'],
          },
          {
            id: 'nootropics',
            name: 'Nootropics',
            category: 'health',
            subcategory: 'longevity',
            searchKeywords: ['nootropics', 'smart drugs', 'cognitive enhancement', 'brain supplements'],
          },
          {
            id: 'hormone-optimization',
            name: 'Hormone Optimization',
            category: 'health',
            subcategory: 'longevity',
            searchKeywords: ['hormone optimization', 'testosterone', 'trt', 'hormone health', 'hrt'],
          },
          {
            id: 'cold-exposure',
            name: 'Cold Exposure',
            category: 'health',
            subcategory: 'longevity',
            searchKeywords: ['cold exposure', 'cold plunge', 'ice bath', 'wim hof', 'cold therapy'],
          },
          {
            id: 'sleep-optimization',
            name: 'Sleep Optimization',
            category: 'health',
            subcategory: 'longevity',
            searchKeywords: ['sleep optimization', 'better sleep', 'sleep tips', 'sleep quality', 'insomnia'],
          },
          {
            id: 'red-light-therapy',
            name: 'Red Light Therapy',
            category: 'health',
            subcategory: 'longevity',
            searchKeywords: ['red light therapy', 'photobiomodulation', 'red light', 'light therapy'],
          },
        ],
      },
      {
        id: 'health-conditions',
        name: 'Health Conditions',
        niches: [
          {
            id: 'diabetes',
            name: 'Diabetes Management',
            category: 'health',
            subcategory: 'health-conditions',
            searchKeywords: ['diabetes', 'reverse diabetes', 'diabetes management', 'blood sugar'],
          },
          {
            id: 'autoimmune',
            name: 'Autoimmune Conditions',
            category: 'health',
            subcategory: 'health-conditions',
            searchKeywords: ['autoimmune', 'autoimmune disease', 'autoimmune healing', 'autoimmune diet'],
          },
          {
            id: 'thyroid',
            name: 'Thyroid Health',
            category: 'health',
            subcategory: 'health-conditions',
            searchKeywords: ['thyroid', 'thyroid health', 'hypothyroid', 'hashimotos'],
          },
          {
            id: 'chronic-pain',
            name: 'Chronic Pain',
            category: 'health',
            subcategory: 'health-conditions',
            searchKeywords: ['chronic pain', 'pain management', 'pain relief', 'back pain', 'fibromyalgia'],
          },
          {
            id: 'pcos',
            name: 'PCOS',
            category: 'health',
            subcategory: 'health-conditions',
            searchKeywords: ['pcos', 'polycystic ovary syndrome', 'pcos treatment', 'pcos diet'],
          },
          {
            id: 'menopause',
            name: 'Menopause',
            category: 'health',
            subcategory: 'health-conditions',
            searchKeywords: ['menopause', 'perimenopause', 'menopause symptoms', 'menopause relief'],
          },
          {
            id: 'fertility',
            name: 'Fertility',
            category: 'health',
            subcategory: 'health-conditions',
            searchKeywords: ['fertility', 'get pregnant', 'fertility tips', 'ttc', 'conception'],
          },
          {
            id: 'skin-health',
            name: 'Skin Health',
            category: 'health',
            subcategory: 'health-conditions',
            searchKeywords: ['skin health', 'acne', 'clear skin', 'eczema', 'psoriasis'],
          },
        ],
      },
    ],
  },

  // ============================================
  // RELATIONSHIPS - Dating, Romance, Family, Social
  // ============================================
  {
    id: 'relationships',
    name: 'Relationships',
    icon: '❤️',
    subcategories: [
      {
        id: 'dating',
        name: 'Dating & Attraction',
        niches: [
          {
            id: 'dating-men',
            name: 'Dating Coaching (for Men)',
            category: 'relationships',
            subcategory: 'dating',
            searchKeywords: ['dating advice for men', 'how to get girlfriend', 'attract women', 'dating coach men'],
          },
          {
            id: 'dating-women',
            name: 'Dating Coaching (for Women)',
            category: 'relationships',
            subcategory: 'dating',
            searchKeywords: ['dating advice for women', 'high value woman', 'attract men', 'dating coach women'],
          },
          {
            id: 'online-dating',
            name: 'Online Dating',
            category: 'relationships',
            subcategory: 'dating',
            searchKeywords: ['online dating', 'tinder tips', 'dating apps', 'hinge', 'bumble tips'],
          },
          {
            id: 'confidence-attraction',
            name: 'Confidence & Attraction',
            category: 'relationships',
            subcategory: 'dating',
            searchKeywords: ['confidence with women', 'be more attractive', 'charisma', 'attraction tips'],
          },
          {
            id: 'social-skills-dating',
            name: 'Social Skills for Dating',
            category: 'relationships',
            subcategory: 'dating',
            searchKeywords: ['social skills', 'conversation skills', 'talk to anyone', 'approach anxiety'],
          },
          {
            id: 'dating-over-40',
            name: 'Dating Over 40',
            category: 'relationships',
            subcategory: 'dating',
            searchKeywords: ['dating over 40', 'dating after divorce', 'dating over 50', 'midlife dating'],
          },
          {
            id: 'christian-dating',
            name: 'Christian Dating',
            category: 'relationships',
            subcategory: 'dating',
            searchKeywords: ['christian dating', 'christian singles', 'godly relationship', 'faith based dating'],
          },
        ],
      },
      {
        id: 'romantic-relationships',
        name: 'Romantic Relationships',
        niches: [
          {
            id: 'relationship-coaching',
            name: 'Relationship Coaching',
            category: 'relationships',
            subcategory: 'romantic-relationships',
            searchKeywords: ['relationship advice', 'relationship coaching', 'better relationship', 'relationship tips'],
          },
          {
            id: 'marriage-coaching',
            name: 'Marriage Coaching',
            category: 'relationships',
            subcategory: 'romantic-relationships',
            searchKeywords: ['marriage advice', 'marriage coaching', 'happy marriage', 'save marriage'],
          },
          {
            id: 'couples-communication',
            name: 'Couples Communication',
            category: 'relationships',
            subcategory: 'romantic-relationships',
            searchKeywords: ['couples communication', 'communicate with partner', 'relationship communication'],
          },
          {
            id: 'intimacy',
            name: 'Intimacy & Connection',
            category: 'relationships',
            subcategory: 'romantic-relationships',
            searchKeywords: ['intimacy', 'emotional intimacy', 'relationship intimacy', 'connection in relationship'],
          },
          {
            id: 'affair-recovery',
            name: 'Affair Recovery',
            category: 'relationships',
            subcategory: 'romantic-relationships',
            searchKeywords: ['affair recovery', 'infidelity recovery', 'trust after cheating', 'survive infidelity'],
          },
          {
            id: 'attachment-styles',
            name: 'Attachment Styles',
            category: 'relationships',
            subcategory: 'romantic-relationships',
            searchKeywords: ['attachment style', 'anxious attachment', 'avoidant attachment', 'attachment theory'],
          },
          {
            id: 'breakup-recovery',
            name: 'Breakup Recovery',
            category: 'relationships',
            subcategory: 'romantic-relationships',
            searchKeywords: ['breakup recovery', 'get over ex', 'heal from breakup', 'move on'],
          },
          {
            id: 'divorce-recovery',
            name: 'Divorce Recovery',
            category: 'relationships',
            subcategory: 'romantic-relationships',
            searchKeywords: ['divorce recovery', 'life after divorce', 'heal from divorce', 'divorce support'],
          },
        ],
      },
      {
        id: 'masculinity-femininity',
        name: 'Masculinity & Femininity',
        niches: [
          {
            id: 'masculinity',
            name: 'Masculinity',
            category: 'relationships',
            subcategory: 'masculinity-femininity',
            searchKeywords: ['masculinity', 'be a man', 'masculine energy', 'manhood', 'alpha male'],
          },
          {
            id: 'femininity',
            name: 'Femininity',
            category: 'relationships',
            subcategory: 'masculinity-femininity',
            searchKeywords: ['femininity', 'feminine energy', 'embrace femininity', 'divine feminine'],
          },
          {
            id: 'mens-self-improvement',
            name: "Men's Self Improvement",
            category: 'relationships',
            subcategory: 'masculinity-femininity',
            searchKeywords: ['mens self improvement', 'level up as a man', 'become better man', 'self improvement men'],
          },
          {
            id: 'womens-self-improvement',
            name: "Women's Self Improvement",
            category: 'relationships',
            subcategory: 'masculinity-femininity',
            searchKeywords: ['self improvement women', 'glow up', 'become high value woman', 'level up woman'],
          },
        ],
      },
      {
        id: 'family-parenting',
        name: 'Family & Parenting',
        niches: [
          {
            id: 'parenting',
            name: 'Parenting',
            category: 'relationships',
            subcategory: 'family-parenting',
            searchKeywords: ['parenting', 'parenting tips', 'parenting advice', 'raise kids'],
          },
          {
            id: 'positive-parenting',
            name: 'Positive Parenting',
            category: 'relationships',
            subcategory: 'family-parenting',
            searchKeywords: ['positive parenting', 'gentle parenting', 'conscious parenting', 'peaceful parenting'],
          },
          {
            id: 'toddler-parenting',
            name: 'Toddler Parenting',
            category: 'relationships',
            subcategory: 'family-parenting',
            searchKeywords: ['toddler parenting', 'toddler tips', 'terrible twos', 'toddler behavior'],
          },
          {
            id: 'teen-parenting',
            name: 'Parenting Teenagers',
            category: 'relationships',
            subcategory: 'family-parenting',
            searchKeywords: ['parenting teens', 'teenager parenting', 'raising teenagers', 'teen behavior'],
          },
          {
            id: 'single-parenting',
            name: 'Single Parenting',
            category: 'relationships',
            subcategory: 'family-parenting',
            searchKeywords: ['single parent', 'single mom', 'single dad', 'solo parenting'],
          },
          {
            id: 'homeschooling',
            name: 'Homeschooling',
            category: 'relationships',
            subcategory: 'family-parenting',
            searchKeywords: ['homeschooling', 'homeschool', 'home education', 'homeschool tips'],
          },
          {
            id: 'new-parents',
            name: 'New Parents',
            category: 'relationships',
            subcategory: 'family-parenting',
            searchKeywords: ['new parent', 'first time parent', 'newborn tips', 'baby care'],
          },
          {
            id: 'co-parenting',
            name: 'Co-Parenting',
            category: 'relationships',
            subcategory: 'family-parenting',
            searchKeywords: ['co parenting', 'coparenting', 'co parent', 'shared custody'],
          },
        ],
      },
      {
        id: 'social-skills',
        name: 'Social & Communication',
        niches: [
          {
            id: 'social-skills',
            name: 'Social Skills',
            category: 'relationships',
            subcategory: 'social-skills',
            searchKeywords: ['social skills', 'be more social', 'improve social skills', 'social confidence'],
          },
          {
            id: 'conversation-skills',
            name: 'Conversation Skills',
            category: 'relationships',
            subcategory: 'social-skills',
            searchKeywords: ['conversation skills', 'how to talk to people', 'small talk', 'be better conversationalist'],
          },
          {
            id: 'making-friends',
            name: 'Making Friends',
            category: 'relationships',
            subcategory: 'social-skills',
            searchKeywords: ['make friends', 'making friends as adult', 'how to make friends', 'find friends'],
          },
          {
            id: 'social-anxiety',
            name: 'Social Anxiety',
            category: 'relationships',
            subcategory: 'social-skills',
            searchKeywords: ['social anxiety', 'overcome social anxiety', 'shy', 'social phobia'],
          },
          {
            id: 'introvert',
            name: 'Introvert Thriving',
            category: 'relationships',
            subcategory: 'social-skills',
            searchKeywords: ['introvert', 'introvert tips', 'introvert social', 'introvert success'],
          },
          {
            id: 'charisma',
            name: 'Charisma & Influence',
            category: 'relationships',
            subcategory: 'social-skills',
            searchKeywords: ['charisma', 'be charismatic', 'influence', 'persuasion', 'likeable'],
          },
          {
            id: 'networking',
            name: 'Networking',
            category: 'relationships',
            subcategory: 'social-skills',
            searchKeywords: ['networking', 'business networking', 'how to network', 'build network'],
          },
          {
            id: 'assertiveness',
            name: 'Assertiveness',
            category: 'relationships',
            subcategory: 'social-skills',
            searchKeywords: ['assertiveness', 'be assertive', 'assertive communication', 'stand up for yourself'],
          },
        ],
      },
    ],
  },

  // ============================================
  // SKILLS & CREATIVITY
  // ============================================
  {
    id: 'skills',
    name: 'Skills & Creativity',
    icon: '🎨',
    subcategories: [
      {
        id: 'content-platforms',
        name: 'Content Platform Growth',
        niches: [
          {
            id: 'youtube-growth',
            name: 'YouTube Growth',
            category: 'skills',
            subcategory: 'content-platforms',
            searchKeywords: ['youtube growth', 'grow youtube channel', 'youtube tips', 'youtube algorithm'],
          },
          {
            id: 'tiktok-growth',
            name: 'TikTok Growth',
            category: 'skills',
            subcategory: 'content-platforms',
            searchKeywords: ['tiktok growth', 'grow on tiktok', 'tiktok algorithm', 'tiktok tips'],
          },
          {
            id: 'instagram-growth',
            name: 'Instagram Growth',
            category: 'skills',
            subcategory: 'content-platforms',
            searchKeywords: ['instagram growth', 'grow instagram', 'instagram tips', 'instagram reels'],
          },
          {
            id: 'twitter-growth',
            name: 'Twitter/X Growth',
            category: 'skills',
            subcategory: 'content-platforms',
            searchKeywords: ['twitter growth', 'x growth', 'grow on twitter', 'twitter tips'],
          },
          {
            id: 'linkedin-growth',
            name: 'LinkedIn Growth',
            category: 'skills',
            subcategory: 'content-platforms',
            searchKeywords: ['linkedin growth', 'linkedin tips', 'linkedin content', 'grow linkedin'],
          },
          {
            id: 'podcast-growth',
            name: 'Podcast Growth',
            category: 'skills',
            subcategory: 'content-platforms',
            searchKeywords: ['podcast growth', 'grow podcast', 'podcast tips', 'podcast marketing'],
          },
          {
            id: 'twitch-streaming',
            name: 'Twitch Streaming',
            category: 'skills',
            subcategory: 'content-platforms',
            searchKeywords: ['twitch streaming', 'grow on twitch', 'twitch tips', 'streaming tips'],
          },
        ],
      },
      {
        id: 'video-production',
        name: 'Video Production',
        niches: [
          {
            id: 'video-editing',
            name: 'Video Editing',
            category: 'skills',
            subcategory: 'video-production',
            searchKeywords: ['video editing', 'premiere pro', 'final cut pro', 'davinci resolve', 'edit videos'],
          },
          {
            id: 'filmmaking',
            name: 'Filmmaking',
            category: 'skills',
            subcategory: 'video-production',
            searchKeywords: ['filmmaking', 'cinematography', 'film school', 'make films', 'director'],
          },
          {
            id: 'videography',
            name: 'Videography',
            category: 'skills',
            subcategory: 'video-production',
            searchKeywords: ['videography', 'video production', 'shoot video', 'camera work'],
          },
          {
            id: 'youtube-production',
            name: 'YouTube Production',
            category: 'skills',
            subcategory: 'video-production',
            searchKeywords: ['youtube production', 'youtube video editing', 'youtube thumbnails', 'youtube setup'],
          },
          {
            id: 'motion-graphics',
            name: 'Motion Graphics',
            category: 'skills',
            subcategory: 'video-production',
            searchKeywords: ['motion graphics', 'after effects', 'motion design', 'animation'],
          },
        ],
      },
      {
        id: 'photography',
        name: 'Photography',
        niches: [
          {
            id: 'photography',
            name: 'Photography',
            category: 'skills',
            subcategory: 'photography',
            searchKeywords: ['photography', 'photography tutorial', 'learn photography', 'camera settings'],
          },
          {
            id: 'portrait-photography',
            name: 'Portrait Photography',
            category: 'skills',
            subcategory: 'photography',
            searchKeywords: ['portrait photography', 'portrait tips', 'portrait lighting'],
          },
          {
            id: 'landscape-photography',
            name: 'Landscape Photography',
            category: 'skills',
            subcategory: 'photography',
            searchKeywords: ['landscape photography', 'landscape tips', 'nature photography'],
          },
          {
            id: 'product-photography',
            name: 'Product Photography',
            category: 'skills',
            subcategory: 'photography',
            searchKeywords: ['product photography', 'ecommerce photography', 'product photos'],
          },
          {
            id: 'photo-editing',
            name: 'Photo Editing',
            category: 'skills',
            subcategory: 'photography',
            searchKeywords: ['photo editing', 'lightroom', 'photoshop', 'edit photos'],
          },
        ],
      },
      {
        id: 'design',
        name: 'Design',
        niches: [
          {
            id: 'graphic-design',
            name: 'Graphic Design',
            category: 'skills',
            subcategory: 'design',
            searchKeywords: ['graphic design', 'learn graphic design', 'design tutorial', 'canva'],
          },
          {
            id: 'ui-ux-design',
            name: 'UI/UX Design',
            category: 'skills',
            subcategory: 'design',
            searchKeywords: ['ui design', 'ux design', 'ui ux', 'figma', 'product design'],
          },
          {
            id: 'web-design',
            name: 'Web Design',
            category: 'skills',
            subcategory: 'design',
            searchKeywords: ['web design', 'website design', 'webflow', 'website builder'],
          },
          {
            id: 'logo-design',
            name: 'Logo Design',
            category: 'skills',
            subcategory: 'design',
            searchKeywords: ['logo design', 'design logo', 'brand identity', 'logo tutorial'],
          },
          {
            id: '3d-design',
            name: '3D Design',
            category: 'skills',
            subcategory: 'design',
            searchKeywords: ['3d design', 'blender', '3d modeling', 'cinema 4d', '3d art'],
          },
          {
            id: 'interior-design',
            name: 'Interior Design',
            category: 'skills',
            subcategory: 'design',
            searchKeywords: ['interior design', 'home design', 'room design', 'interior decorating'],
          },
        ],
      },
      {
        id: 'music',
        name: 'Music',
        niches: [
          {
            id: 'music-production',
            name: 'Music Production',
            category: 'skills',
            subcategory: 'music',
            searchKeywords: ['music production', 'make beats', 'produce music', 'fl studio', 'ableton'],
          },
          {
            id: 'guitar',
            name: 'Guitar',
            category: 'skills',
            subcategory: 'music',
            searchKeywords: ['guitar', 'learn guitar', 'guitar lessons', 'guitar tutorial'],
          },
          {
            id: 'piano',
            name: 'Piano',
            category: 'skills',
            subcategory: 'music',
            searchKeywords: ['piano', 'learn piano', 'piano lessons', 'piano tutorial'],
          },
          {
            id: 'singing',
            name: 'Singing',
            category: 'skills',
            subcategory: 'music',
            searchKeywords: ['singing', 'learn to sing', 'vocal lessons', 'improve singing'],
          },
          {
            id: 'songwriting',
            name: 'Songwriting',
            category: 'skills',
            subcategory: 'music',
            searchKeywords: ['songwriting', 'write songs', 'songwriting tips', 'lyrics'],
          },
          {
            id: 'djing',
            name: 'DJing',
            category: 'skills',
            subcategory: 'music',
            searchKeywords: ['dj', 'djing', 'learn to dj', 'dj tutorial', 'mixing'],
          },
        ],
      },
      {
        id: 'writing',
        name: 'Writing',
        niches: [
          {
            id: 'writing',
            name: 'Writing',
            category: 'skills',
            subcategory: 'writing',
            searchKeywords: ['writing', 'become writer', 'writing tips', 'improve writing'],
          },
          {
            id: 'fiction-writing',
            name: 'Fiction Writing',
            category: 'skills',
            subcategory: 'writing',
            searchKeywords: ['fiction writing', 'write novel', 'creative writing', 'storytelling'],
          },
          {
            id: 'screenwriting',
            name: 'Screenwriting',
            category: 'skills',
            subcategory: 'writing',
            searchKeywords: ['screenwriting', 'write screenplay', 'script writing', 'screenwriter'],
          },
          {
            id: 'blogging',
            name: 'Blogging',
            category: 'skills',
            subcategory: 'writing',
            searchKeywords: ['blogging', 'start blog', 'blog writing', 'make money blogging'],
          },
          {
            id: 'self-publishing',
            name: 'Self-Publishing',
            category: 'skills',
            subcategory: 'writing',
            searchKeywords: ['self publishing', 'publish book', 'amazon kdp', 'ebook publishing'],
          },
        ],
      },
      {
        id: 'tech-skills',
        name: 'Tech Skills',
        niches: [
          {
            id: 'coding',
            name: 'Coding / Programming',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['coding', 'programming', 'learn to code', 'software development'],
          },
          {
            id: 'python',
            name: 'Python',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['python', 'learn python', 'python tutorial', 'python programming'],
          },
          {
            id: 'javascript',
            name: 'JavaScript',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['javascript', 'learn javascript', 'js tutorial', 'web development'],
          },
          {
            id: 'web-development',
            name: 'Web Development',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['web development', 'full stack', 'frontend', 'backend', 'web dev'],
          },
          {
            id: 'app-development',
            name: 'App Development',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['app development', 'mobile app', 'ios development', 'android development'],
          },
          {
            id: 'no-code',
            name: 'No-Code Development',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['no code', 'bubble', 'webflow', 'no code app', 'build without code'],
          },
          {
            id: 'ai-tools',
            name: 'AI Tools',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['ai tools', 'chatgpt', 'midjourney', 'ai for business', 'ai automation'],
          },
          {
            id: 'prompt-engineering',
            name: 'Prompt Engineering',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['prompt engineering', 'chatgpt prompts', 'ai prompts', 'prompt writing'],
          },
          {
            id: 'data-analysis',
            name: 'Data Analysis',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['data analysis', 'excel', 'data analytics', 'sql', 'power bi'],
          },
          {
            id: 'automation',
            name: 'Automation',
            category: 'skills',
            subcategory: 'tech-skills',
            searchKeywords: ['automation', 'zapier', 'make', 'automate tasks', 'workflow automation'],
          },
        ],
      },
      {
        id: 'languages',
        name: 'Language Learning',
        niches: [
          {
            id: 'spanish',
            name: 'Spanish',
            category: 'skills',
            subcategory: 'languages',
            searchKeywords: ['learn spanish', 'spanish lessons', 'spanish for beginners', 'speak spanish'],
          },
          {
            id: 'french',
            name: 'French',
            category: 'skills',
            subcategory: 'languages',
            searchKeywords: ['learn french', 'french lessons', 'french for beginners', 'speak french'],
          },
          {
            id: 'german',
            name: 'German',
            category: 'skills',
            subcategory: 'languages',
            searchKeywords: ['learn german', 'german lessons', 'german for beginners', 'speak german'],
          },
          {
            id: 'japanese',
            name: 'Japanese',
            category: 'skills',
            subcategory: 'languages',
            searchKeywords: ['learn japanese', 'japanese lessons', 'japanese for beginners', 'speak japanese'],
          },
          {
            id: 'mandarin',
            name: 'Mandarin Chinese',
            category: 'skills',
            subcategory: 'languages',
            searchKeywords: ['learn chinese', 'mandarin lessons', 'chinese for beginners', 'speak mandarin'],
          },
          {
            id: 'korean',
            name: 'Korean',
            category: 'skills',
            subcategory: 'languages',
            searchKeywords: ['learn korean', 'korean lessons', 'korean for beginners', 'speak korean'],
          },
          {
            id: 'english',
            name: 'English (ESL)',
            category: 'skills',
            subcategory: 'languages',
            searchKeywords: ['learn english', 'english lessons', 'esl', 'improve english', 'english speaking'],
          },
        ],
      },
    ],
  },

  // ============================================
  // LIFESTYLE
  // ============================================
  {
    id: 'lifestyle',
    name: 'Lifestyle',
    icon: '🏠',
    subcategories: [
      {
        id: 'fashion-style',
        name: 'Fashion & Style',
        niches: [
          {
            id: 'mens-fashion',
            name: "Men's Fashion",
            category: 'lifestyle',
            subcategory: 'fashion-style',
            searchKeywords: ['mens fashion', 'mens style', 'how to dress men', 'mens wardrobe'],
          },
          {
            id: 'womens-fashion',
            name: "Women's Fashion",
            category: 'lifestyle',
            subcategory: 'fashion-style',
            searchKeywords: ['womens fashion', 'womens style', 'how to dress', 'wardrobe tips'],
          },
          {
            id: 'personal-styling',
            name: 'Personal Styling',
            category: 'lifestyle',
            subcategory: 'fashion-style',
            searchKeywords: ['personal styling', 'style tips', 'find your style', 'style makeover'],
          },
          {
            id: 'capsule-wardrobe',
            name: 'Capsule Wardrobe',
            category: 'lifestyle',
            subcategory: 'fashion-style',
            searchKeywords: ['capsule wardrobe', 'minimalist wardrobe', 'wardrobe essentials'],
          },
          {
            id: 'mens-grooming',
            name: "Men's Grooming",
            category: 'lifestyle',
            subcategory: 'fashion-style',
            searchKeywords: ['mens grooming', 'skincare for men', 'mens haircare', 'grooming tips'],
          },
        ],
      },
      {
        id: 'beauty',
        name: 'Beauty & Skincare',
        niches: [
          {
            id: 'skincare',
            name: 'Skincare',
            category: 'lifestyle',
            subcategory: 'beauty',
            searchKeywords: ['skincare', 'skincare routine', 'clear skin', 'skincare tips'],
          },
          {
            id: 'makeup',
            name: 'Makeup',
            category: 'lifestyle',
            subcategory: 'beauty',
            searchKeywords: ['makeup', 'makeup tutorial', 'makeup tips', 'beauty'],
          },
          {
            id: 'haircare',
            name: 'Haircare',
            category: 'lifestyle',
            subcategory: 'beauty',
            searchKeywords: ['haircare', 'hair growth', 'hair tips', 'healthy hair'],
          },
          {
            id: 'natural-beauty',
            name: 'Natural Beauty',
            category: 'lifestyle',
            subcategory: 'beauty',
            searchKeywords: ['natural beauty', 'clean beauty', 'organic skincare', 'diy beauty'],
          },
        ],
      },
      {
        id: 'home-living',
        name: 'Home & Living',
        niches: [
          {
            id: 'minimalism',
            name: 'Minimalism',
            category: 'lifestyle',
            subcategory: 'home-living',
            searchKeywords: ['minimalism', 'minimalist lifestyle', 'declutter', 'simple living'],
          },
          {
            id: 'organization',
            name: 'Home Organization',
            category: 'lifestyle',
            subcategory: 'home-living',
            searchKeywords: ['home organization', 'organize home', 'decluttering', 'tidy home'],
          },
          {
            id: 'home-improvement',
            name: 'Home Improvement / DIY',
            category: 'lifestyle',
            subcategory: 'home-living',
            searchKeywords: ['home improvement', 'diy home', 'home renovation', 'diy projects'],
          },
          {
            id: 'gardening',
            name: 'Gardening',
            category: 'lifestyle',
            subcategory: 'home-living',
            searchKeywords: ['gardening', 'garden tips', 'vegetable garden', 'grow plants'],
          },
          {
            id: 'homesteading',
            name: 'Homesteading',
            category: 'lifestyle',
            subcategory: 'home-living',
            searchKeywords: ['homesteading', 'homestead', 'self sufficient', 'off grid'],
          },
          {
            id: 'sustainable-living',
            name: 'Sustainable Living',
            category: 'lifestyle',
            subcategory: 'home-living',
            searchKeywords: ['sustainable living', 'eco friendly', 'zero waste', 'green living'],
          },
        ],
      },
      {
        id: 'travel',
        name: 'Travel',
        niches: [
          {
            id: 'travel-hacking',
            name: 'Travel Hacking',
            category: 'lifestyle',
            subcategory: 'travel',
            searchKeywords: ['travel hacking', 'travel points', 'free travel', 'credit card points'],
          },
          {
            id: 'budget-travel',
            name: 'Budget Travel',
            category: 'lifestyle',
            subcategory: 'travel',
            searchKeywords: ['budget travel', 'cheap travel', 'travel on budget', 'affordable travel'],
          },
          {
            id: 'digital-nomad',
            name: 'Digital Nomad',
            category: 'lifestyle',
            subcategory: 'travel',
            searchKeywords: ['digital nomad', 'work and travel', 'remote work travel', 'nomad lifestyle'],
          },
          {
            id: 'van-life',
            name: 'Van Life',
            category: 'lifestyle',
            subcategory: 'travel',
            searchKeywords: ['van life', 'vanlife', 'live in van', 'van conversion'],
          },
          {
            id: 'expat-life',
            name: 'Expat Life',
            category: 'lifestyle',
            subcategory: 'travel',
            searchKeywords: ['expat', 'move abroad', 'live abroad', 'expatriate'],
          },
        ],
      },
      {
        id: 'cooking-food',
        name: 'Cooking & Food',
        niches: [
          {
            id: 'cooking',
            name: 'Cooking',
            category: 'lifestyle',
            subcategory: 'cooking-food',
            searchKeywords: ['cooking', 'learn to cook', 'cooking tutorial', 'recipes'],
          },
          {
            id: 'baking',
            name: 'Baking',
            category: 'lifestyle',
            subcategory: 'cooking-food',
            searchKeywords: ['baking', 'baking tutorial', 'how to bake', 'baking recipes'],
          },
          {
            id: 'healthy-cooking',
            name: 'Healthy Cooking',
            category: 'lifestyle',
            subcategory: 'cooking-food',
            searchKeywords: ['healthy cooking', 'healthy recipes', 'clean eating recipes', 'healthy meals'],
          },
          {
            id: 'meal-prep-cooking',
            name: 'Meal Prep',
            category: 'lifestyle',
            subcategory: 'cooking-food',
            searchKeywords: ['meal prep', 'meal prepping', 'weekly meal prep', 'batch cooking'],
          },
        ],
      },
      {
        id: 'pets',
        name: 'Pets',
        niches: [
          {
            id: 'dog-training',
            name: 'Dog Training',
            category: 'lifestyle',
            subcategory: 'pets',
            searchKeywords: ['dog training', 'train dog', 'puppy training', 'dog behavior'],
          },
          {
            id: 'cat-care',
            name: 'Cat Care',
            category: 'lifestyle',
            subcategory: 'pets',
            searchKeywords: ['cat care', 'cat tips', 'cat behavior', 'cat training'],
          },
          {
            id: 'pet-care',
            name: 'Pet Care',
            category: 'lifestyle',
            subcategory: 'pets',
            searchKeywords: ['pet care', 'pet health', 'pet tips', 'pet owner'],
          },
        ],
      },
    ],
  },
];

// Helper function to get all niches as a flat array
export function getAllNiches(): Niche[] {
  const niches: Niche[] = [];
  for (const category of NICHE_CATEGORIES) {
    for (const subcategory of category.subcategories) {
      niches.push(...subcategory.niches);
    }
  }
  return niches;
}

// Helper function to get niche by ID
export function getNicheById(id: string): Niche | undefined {
  return getAllNiches().find((niche) => niche.id === id);
}

// Helper function to search niches by query
export function searchNiches(query: string): Niche[] {
  const lowerQuery = query.toLowerCase();
  return getAllNiches().filter(
    (niche) =>
      niche.name.toLowerCase().includes(lowerQuery) ||
      niche.searchKeywords.some((kw) => kw.toLowerCase().includes(lowerQuery))
  );
}

// Get count of niches
export function getNicheCount(): number {
  return getAllNiches().length;
}
